name: Daily URL Access

on:
  workflow_dispatch:  # 手動トリガー
  schedule:
    # 毎日18:00 (UTC) に実行
    - cron: "0 18 * * *"

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP GET request
        run: curl -X GET "https://kamoyan-seatassign.streamlit.app/"

